blank_issues_enabled: false
contact_links:
  - name: Geen GitHub-account? / No GitHub account?
    url: mailto:planoradevelopment@outlook.com
    about: Mail je melding naar planoradevelopment@outlook.com. / E-mail your report to planoradevelopment@outlook.com.
